version: '3.8'

services:
  epitome:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - nginx_cache:/var/cache/nginx
    networks:
      - epitome-network

  # Optional: Add a simple reverse proxy with caching if needed
  # nginx-cache:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./docker/nginx/nginx-cache.conf:/etc/nginx/conf.d/default.conf
  #     - nginx_cache:/var/cache/nginx
  #   depends_on:
  #     - epitome
  #   networks:
  #     - epitome-network
  #   restart: unless-stopped

volumes:
  nginx_cache:

networks:
  epitome-network: 